# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from soc/BatteryGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BatteryGoal(genpy.Message):
  _md5sum = "875cbb9722d1f560aa70e6256c1a449d"
  _type = "soc/BatteryGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
int32 samples
int8 batteryState
float64 batteryCapacity
float64 chargeCurrentLimit
float64 dischargeCurrentLimit
"""
  __slots__ = ['samples','batteryState','batteryCapacity','chargeCurrentLimit','dischargeCurrentLimit']
  _slot_types = ['int32','int8','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       samples,batteryState,batteryCapacity,chargeCurrentLimit,dischargeCurrentLimit

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BatteryGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.samples is None:
        self.samples = 0
      if self.batteryState is None:
        self.batteryState = 0
      if self.batteryCapacity is None:
        self.batteryCapacity = 0.
      if self.chargeCurrentLimit is None:
        self.chargeCurrentLimit = 0.
      if self.dischargeCurrentLimit is None:
        self.dischargeCurrentLimit = 0.
    else:
      self.samples = 0
      self.batteryState = 0
      self.batteryCapacity = 0.
      self.chargeCurrentLimit = 0.
      self.dischargeCurrentLimit = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_ib3d().pack(_x.samples, _x.batteryState, _x.batteryCapacity, _x.chargeCurrentLimit, _x.dischargeCurrentLimit))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.samples, _x.batteryState, _x.batteryCapacity, _x.chargeCurrentLimit, _x.dischargeCurrentLimit,) = _get_struct_ib3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_ib3d().pack(_x.samples, _x.batteryState, _x.batteryCapacity, _x.chargeCurrentLimit, _x.dischargeCurrentLimit))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.samples, _x.batteryState, _x.batteryCapacity, _x.chargeCurrentLimit, _x.dischargeCurrentLimit,) = _get_struct_ib3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_ib3d = None
def _get_struct_ib3d():
    global _struct_ib3d
    if _struct_ib3d is None:
        _struct_ib3d = struct.Struct("<ib3d")
    return _struct_ib3d
